### ISSUE TITLE
pytorch 0.4.1 and cuda < 9.2

### ISSUE THREAD

**Issue by faroit** [Con-Mi/Pattern-Recognition-and-Machine-Learning#1]
Hi, I just found your notebooks to be very helpful.

One question regarding the colab pytorch 0.4.1 example: it seems to be pretty hacky to install cuda 9.2 in colab. Does pytorch 0.4.1 also works with the preinstalled cuda version so I don't have to use these tricks?

**Comment by Con-Mi** [comment]
Yes you don't really need to get the latest cuda version for PyTorch on the Colab environment. You can just use 'pip' to install it. The Colab comes with cuda 8.  Check tthe commands on this link to get it https://pytorch.org/
